### ISSUE TITLE
Dropdown menu symbol upside down in Navbar

### ISSUE THREAD

**Issue by SrinivasJoshi** [pooltogether/pooltogether.com#11]
Reproduce the issue : 
1. Click on hamburger menu on Navbar after connecting wallet

<img width="420" alt="Screenshot 2023-07-06 at 2 53 04 PM" src="https://github.com/pooltogether/pooltogether.com/assets/69837749/a502f4a6-ea24-4e0c-84a1-dabb00249eb8">

I hope this helps :)

**Comment by Ncookiez** [comment]
Ah, this is on the app itself, not this repo (the landing page). I'd argue that it's actually the correct way up, since the content flows upwards, not downwards if you open them. Maybe not the most intuitive icons though 😅
